# ==========================================================
# Makefile build 'Remove duplicates project' using Make
# ==========================================================
all:
	g++ -Wall -std=c++0x src/drive.cpp -I include/ -o bin/rDuplicates -g

val:
	valgrind ../bin/rDuplicates