# ==========================================================
# Makefile build 'Balanced Parenthesis project' using Make
# ==========================================================
all:
	g++ -Wall -std=c++0x src/drive.cpp -I include/ -I lib/ -o bin/bParenthesis -g

val:
	valgrind ../bin/bParenthesis