# ====================================================
# Makefile build 'Stack project' using Make
# ====================================================
all:
	g++ -Wall -std=c++0x src/drive.cpp -I include/ -I ../../../Array/include/ -o bin/stackLL -g

val:
	valgrind ../bin/stackLL