# ==============================================================
# Makefile build 'RPN expression evaluation project' using Make
# ==============================================================
all:
	g++ -Wall -std=c++0x src/drive.cpp -I include/ -I ../lib/ -o bin/rpnEvaluator -g

val:
	valgrind ../bin/rpnEvaluator