# ====================================================================
# Makefile build 'Remove All Adjacent Duplicates project' using Make
# ====================================================================
all:
	g++ -Wall -std=c++0x src/drive.cpp -I include/ -I ../lib/ -o bin/removeAdjacent -g

val:
	valgrind ../bin/removeAdjacent