# ====================================================
# Makefile build 'Array project' using Make
# ====================================================
all:
	g++ -Wall -std=c++11 src/drive.cpp -I include/ -o bin/TopNumCompetitors -g

val:
	valgrind ../bin/TopNumCompetitors