# ==========================================================
# Makefile build 'Fresh Promo project' using Make
# ==========================================================
all:
	g++ -Wall -std=c++0x src/drive.cpp -I include/ -I ../lib/ -o bin/freshPromo -g

val:
	valgrind ../bin/freshPromo